### ISSUE TITLE
Please add tests of server-side logic

### ISSUE THREAD

**Issue by mrtnzlml** [ooolushaa/t9#1]
Hi Pavel 👋 - thanks for submitting your solution. Before I can start actually checking it I miss one important thing: unit tests of the server-side logic.

Can you please add them so we are sure you know how to write these tests? Also, think about how would you test client code if requested.

Thank you very much... 🙂

**Comment by pzhukau** [comment]
Hey @mrtnzlml. Thanks for a good point 👍
Backend tests already in the repo.

**Comment by mrtnzlml** [comment]
Thanks. We'll let you know.
